export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type ContentStatus = 'draft' | 'in_review' | 'published' | 'archived';
export type UserRole = 'super_admin' | 'admin' | 'editor' | 'viewer';
export type SocialPlatform = 'facebook' | 'x' | 'youtube' | 'instagram' | 'linkedin' | 'whatsapp';
export type ImageAspectRatio = '4/5' | '4/6' | '1/1' | '3/4' | '21/9' | '16/9';
export type ContentLanguage = 'mr' | 'en';
export type OpenBehaviour = 'image' | 'document' | 'detail';
export type InitiativeStatus = 'ongoing' | 'completed' | 'planned';
export type MediaType = 'news' | 'interview' | 'podcast' | 'video' | 'tv' | 'print' | 'digital' | 'press_statement' | 'social_video';
export type MediaPlatform = 'youtube' | 'facebook' | 'instagram' | 'x' | 'website' | 'other';
export type ThumbnailMode = 'auto_youtube' | 'uploaded' | 'generated';
export type MediaOrientation = 'landscape' | 'portrait';
export type VideoCategory = 'interview' | 'speech' | 'awareness' | 'event' | 'discussion' | 'campaign';
export type DocumentVisibility = 'public' | 'private';
export type ConcernStatus = 'new' | 'under_review' | 'representation_made' | 'authority_response' | 'resolved' | 'closed';
export type RequestStatus = 'new' | 'in_progress' | 'completed' | 'archived';

export interface Database {
  public: {
    Tables: {
      app_users: {
        Row: {
          id: string;
          email: string;
          role: UserRole;
          is_active: boolean;
          mfa_enforced: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: UserRole;
          is_active?: boolean;
          mfa_enforced?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: UserRole;
          is_active?: boolean;
          mfa_enforced?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      site_profile: {
        Row: {
          id: number;
          full_name: string;
          display_first_name: string;
          display_last_name: string;
          designation: string;
          tagline: string | null;
          hero_video_path: string | null;
          hero_poster_path: string | null;
          hero_overlay_opacity: number;
          portrait_1_path: string;
          portrait_1_alt: string;
          portrait_2_path: string | null;
          portrait_2_alt: string | null;
          intro_paragraph_1: Json;
          intro_paragraph_2: Json;
          story_video_path: string | null;
          story_poster_path: string | null;
          story_youtube_id: string | null;
          about_eyebrow: string;
          about_heading: string;
          about_heading_accent: string | null;
          about_paragraph_1: Json | null;
          about_paragraph_2: Json | null;
          about_statement: Json | null;
          about_banner_path: string | null;
          about_banner_alt: string | null;
          expertise_eyebrow: string;
          expertise_heading: string;
          expertise_heading_accent: string | null;
          expertise_paragraph_1: Json | null;
          expertise_paragraph_2: Json | null;
          topics_label: string;
          journey_heading: string;
          journey_heading_accent: string;
          long_bio: Json | null;
          mission: string | null;
          vision: string | null;
          philosophy: string | null;
          press_bio_short: string | null;
          press_bio_long: string | null;
          contact_email: string;
          contact_phone: string | null;
          show_phone: boolean;
          office_address: string | null;
          show_address: boolean;
          footer_display_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          full_name: string;
          display_first_name?: string;
          display_last_name?: string;
          designation?: string;
          tagline?: string | null;
          hero_video_path?: string | null;
          hero_poster_path?: string | null;
          hero_overlay_opacity?: number;
          portrait_1_path: string;
          portrait_1_alt: string;
          portrait_2_path?: string | null;
          portrait_2_alt?: string | null;
          intro_paragraph_1: Json;
          intro_paragraph_2: Json;
          story_video_path?: string | null;
          story_poster_path?: string | null;
          story_youtube_id?: string | null;
          about_eyebrow?: string;
          about_heading: string;
          about_heading_accent?: string | null;
          about_paragraph_1?: Json | null;
          about_paragraph_2?: Json | null;
          about_statement?: Json | null;
          about_banner_path?: string | null;
          about_banner_alt?: string | null;
          expertise_eyebrow?: string;
          expertise_heading: string;
          expertise_heading_accent?: string | null;
          expertise_paragraph_1?: Json | null;
          expertise_paragraph_2?: Json | null;
          topics_label?: string;
          journey_heading?: string;
          journey_heading_accent?: string;
          long_bio?: Json | null;
          mission?: string | null;
          vision?: string | null;
          philosophy?: string | null;
          press_bio_short?: string | null;
          press_bio_long?: string | null;
          contact_email: string;
          contact_phone?: string | null;
          show_phone?: boolean;
          office_address?: string | null;
          show_address?: boolean;
          footer_display_name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['site_profile']['Insert']>;
      };
      social_links: {
        Row: {
          id: string;
          platform: SocialPlatform;
          url: string;
          label: string | null;
          is_verified: boolean;
          is_active: boolean;
          show_in_header: boolean;
          show_in_footer: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          platform: SocialPlatform;
          url: string;
          label?: string | null;
          is_verified?: boolean;
          is_active?: boolean;
          show_in_header?: boolean;
          show_in_footer?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['social_links']['Insert']>;
      };
      impact_areas: {
        Row: {
          id: string;
          title: string;
          slug: string;
          short_description: string | null;
          overview: Json | null;
          involvement: Json | null;
          hero_image_path: string | null;
          icon: string | null;
          is_topic: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          short_description?: string | null;
          overview?: Json | null;
          involvement?: Json | null;
          hero_image_path?: string | null;
          icon?: string | null;
          is_topic?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['impact_areas']['Insert']>;
      };
      site_settings: {
        Row: {
          id: number;
          site_name: string;
          theme: Json;
          default_og_image: string | null;
          ga4_id: string | null;
          whatsapp_number: string | null;
          copyright_name: string;
          impact_counters: Json;
          notification_emails: Json;
          response_window_text: string | null;
          concern_disclaimer_text: string | null;
          consent_text: string | null;
          consent_text_version: string;
          privacy_policy: string | null;
          terms: string | null;
          disclaimer: string | null;
          maintenance_mode: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          site_name?: string;
          theme?: Json;
          default_og_image?: string | null;
          ga4_id?: string | null;
          whatsapp_number?: string | null;
          copyright_name?: string;
          impact_counters?: Json;
          notification_emails?: Json;
          response_window_text?: string | null;
          concern_disclaimer_text?: string | null;
          consent_text?: string | null;
          consent_text_version?: string;
          privacy_policy?: string | null;
          terms?: string | null;
          disclaimer?: string | null;
          maintenance_mode?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['site_settings']['Insert']>;
      };
      journey_milestones: {
        Row: {
          id: string;
          label: string | null;
          title: string;
          description: string;
          body: string | null;
          start_year: number;
          start_month: number | null;
          end_year: number | null;
          end_month: number | null;
          is_current: boolean;
          image_path: string;
          image_alt: string;
          image_aspect: ImageAspectRatio;
          grayscale_default: boolean;
          sort_order: number;
          status: ContentStatus;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label?: string | null;
          title: string;
          description: string;
          body?: string | null;
          start_year: number;
          start_month?: number | null;
          end_year?: number | null;
          end_month?: number | null;
          is_current?: boolean;
          image_path: string;
          image_alt: string;
          image_aspect?: ImageAspectRatio;
          grayscale_default?: boolean;
          sort_order?: number;
          status?: ContentStatus;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['journey_milestones']['Insert']>;
      };
      documents: {
        Row: {
          id: string;
          title: string;
          category: string | null;
          topic: string | null;
          document_date: string | null;
          file_path: string;
          mime: string | null;
          size_bytes: number | null;
          visibility: DocumentVisibility;
          download_count: number;
          status: ContentStatus;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          category?: string | null;
          topic?: string | null;
          document_date?: string | null;
          file_path: string;
          mime?: string | null;
          size_bytes?: number | null;
          visibility?: DocumentVisibility;
          download_count?: number;
          status?: ContentStatus;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['documents']['Insert']>;
      };
      representation_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['representation_categories']['Insert']>;
      };
      representations: {
        Row: {
          id: string;
          number: number;
          title: string;
          title_alt: string | null;
          language: ContentLanguage;
          category_id: string;
          representation_date: string;
          summary: string;
          body: Json | null;
          authority: string | null;
          clipping_image_path: string;
          clipping_image_alt: string;
          source_publication: string | null;
          source_url: string | null;
          document_id: string | null;
          open_behaviour: OpenBehaviour;
          is_featured: boolean;
          status: ContentStatus;
          search_vector: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: number;
          title: string;
          title_alt?: string | null;
          language?: ContentLanguage;
          category_id: string;
          representation_date: string;
          summary: string;
          body?: Json | null;
          authority?: string | null;
          clipping_image_path: string;
          clipping_image_alt: string;
          source_publication?: string | null;
          source_url?: string | null;
          document_id?: string | null;
          open_behaviour?: OpenBehaviour;
          is_featured?: boolean;
          status?: ContentStatus;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['representations']['Insert']>;
      };
      initiative_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['initiative_categories']['Insert']>;
      };
      initiatives: {
        Row: {
          id: string;
          title: string;
          title_alt: string | null;
          slug: string;
          subtitle: string | null;
          category_id: string;
          initiative_status: InitiativeStatus;
          start_date: string | null;
          end_date: string | null;
          location: string | null;
          short_description: string;
          source_publication: string | null;
          source_url: string | null;
          problem_statement: Json | null;
          background: Json | null;
          action_taken: Json | null;
          outcome: Json | null;
          stakeholders: string[];
          featured_image_path: string;
          featured_image_alt: string;
          is_featured: boolean;
          status: ContentStatus;
          published_at: string | null;
          search_vector: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          title_alt?: string | null;
          slug: string;
          subtitle?: string | null;
          category_id: string;
          initiative_status?: InitiativeStatus;
          start_date?: string | null;
          end_date?: string | null;
          location?: string | null;
          short_description: string;
          source_publication?: string | null;
          source_url?: string | null;
          problem_statement?: Json | null;
          background?: Json | null;
          action_taken?: Json | null;
          outcome?: Json | null;
          stakeholders?: string[];
          featured_image_path: string;
          featured_image_alt: string;
          is_featured?: boolean;
          status?: ContentStatus;
          published_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['initiatives']['Insert']>;
      };
      media_items: {
        Row: {
          id: string;
          title: string;
          title_alt: string | null;
          language: ContentLanguage;
          media_type: MediaType;
          platform: MediaPlatform;
          category_label: string | null;
          publication_or_channel: string;
          publication_logo_path: string | null;
          published_on: string;
          author: string | null;
          youtube_id: string | null;
          external_url: string | null;
          thumbnail_mode: ThumbnailMode;
          thumbnail_path: string | null;
          thumbnail_alt: string | null;
          orientation: MediaOrientation;
          description: string | null;
          is_featured: boolean;
          related_initiative_id: string | null;
          related_representation_id: string | null;
          status: ContentStatus;
          search_vector: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          title_alt?: string | null;
          language?: ContentLanguage;
          media_type?: MediaType;
          platform: MediaPlatform;
          category_label?: string | null;
          publication_or_channel: string;
          publication_logo_path?: string | null;
          published_on: string;
          author?: string | null;
          youtube_id?: string | null;
          external_url?: string | null;
          thumbnail_mode?: ThumbnailMode;
          thumbnail_path?: string | null;
          thumbnail_alt?: string | null;
          orientation?: MediaOrientation;
          description?: string | null;
          is_featured?: boolean;
          related_initiative_id?: string | null;
          related_representation_id?: string | null;
          status?: ContentStatus;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['media_items']['Insert']>;
      };
      videos: {
        Row: {
          id: string;
          title: string;
          slug: string;
          youtube_id: string;
          category: VideoCategory;
          recorded_on: string | null;
          description: string | null;
          transcript: string | null;
          is_featured: boolean;
          status: ContentStatus;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          youtube_id: string;
          category?: VideoCategory;
          recorded_on?: string | null;
          description?: string | null;
          transcript?: string | null;
          is_featured?: boolean;
          status?: ContentStatus;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['videos']['Insert']>;
      };
      contact_requests: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string | null;
          organization: string | null;
          message: string;
          status: RequestStatus;
          ip_hash: string | null;
          user_agent: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          phone?: string | null;
          organization?: string | null;
          message: string;
          status?: RequestStatus;
          ip_hash?: string | null;
          user_agent?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['contact_requests']['Insert']>;
      };
      education_concerns: {
        Row: {
          id: string;
          reference_code: string;
          student_name: string | null;
          guardian_name: string;
          relationship: string;
          contact_email: string;
          contact_phone: string;
          school_name: string;
          school_district: string;
          school_city: string;
          concern_category: string;
          incident_date: string | null;
          description: string;
          steps_taken: string | null;
          attachments: Json;
          consent_given: boolean;
          consent_text_version: string;
          status: ConcernStatus;
          internal_notes: string | null;
          assigned_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference_code: string;
          student_name?: string | null;
          guardian_name: string;
          relationship: string;
          contact_email: string;
          contact_phone: string;
          school_name: string;
          school_district: string;
          school_city: string;
          concern_category: string;
          incident_date?: string | null;
          description: string;
          steps_taken?: string | null;
          attachments?: Json;
          consent_given?: boolean;
          consent_text_version?: string;
          status?: ConcernStatus;
          internal_notes?: string | null;
          assigned_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['education_concerns']['Insert']>;
      };
      speaking_requests: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string;
          organization: string;
          event_name: string;
          event_date: string | null;
          topic: string;
          audience_size: number | null;
          venue_city: string;
          details: string | null;
          status: RequestStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          phone: string;
          organization: string;
          event_name: string;
          event_date?: string | null;
          topic: string;
          audience_size?: number | null;
          venue_city: string;
          details?: string | null;
          status?: RequestStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['speaking_requests']['Insert']>;
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_email: string | null;
          action: string;
          entity: string;
          entity_id: string | null;
          diff: Json | null;
          ip_hash: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_email?: string | null;
          action: string;
          entity: string;
          entity_id?: string | null;
          diff?: Json | null;
          ip_hash?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>;
      };
      storage_assets: {
        Row: {
          id: string;
          path: string;
          bucket: string;
          mime: string | null;
          width: number | null;
          height: number | null;
          blurhash: string | null;
          alt: string | null;
          used_by: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          path: string;
          bucket: string;
          mime?: string | null;
          width?: number | null;
          height?: number | null;
          blurhash?: string | null;
          alt?: string | null;
          used_by?: Json;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['storage_assets']['Insert']>;
      };
    };
    Views: {
      public_site_profile: {
        Row: Database['public']['Tables']['site_profile']['Row'];
      };
    };
  };
}
